# Generated by Django 5.2 on 2025-04-23 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooswellapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessGoals',
            fields=[
                ('goals_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hooswellapp.goals')),
                ('activity', models.CharField(max_length=20, null=True)),
                ('target_minutes', models.IntegerField()),
            ],
            options={
                'db_table': 'fitness_goals',
                'managed': True,
            },
            bases=('hooswellapp.goals',),
        ),
        migrations.CreateModel(
            name='SleepGoals',
            fields=[
                ('goals_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hooswellapp.goals')),
                ('target_quality', models.DecimalField(decimal_places=2, max_digits=4)),
                ('target_hours', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'sleep_goals',
                'managed': True,
            },
            bases=('hooswellapp.goals',),
        ),
        migrations.CreateModel(
            name='NutritionGoals',
            fields=[
                ('goals_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hooswellapp.goals')),
                ('lower_grams', models.IntegerField()),
                ('upper_grams', models.IntegerField()),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hooswellapp.foods')),
            ],
            options={
                'db_table': 'nutrition_goals',
                'managed': True,
            },
            bases=('hooswellapp.goals',),
        ),
    ]
